created 5 classes w/ fields and method. As result by using method "getRandomBall" - complete the task.
mate-academy/jv-lottery pull request #1042
Opened 2023-07-24 13:45 UTC by tsuki99

2023-07-24 17:23 UTC, olekskov requested changes

2023-07-24 17:23 UTC, olekskov commented on src/main/java/core/basesyntax/Application.java
>      public static void main(String[] args) {
Our main class shouldn't extend lottery, please create required object instead and use it to call required method further
```suggestion
public class Application {
    public static void main(String[] args) {
    Lottery lottery = new Lottery();
```

2023-07-24 17:23 UTC, olekskov commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
enum class name should be in singular form
```suggestion
public enum Color {
```

2023-07-24 17:23 UTC, olekskov commented on src/main/java/core/basesyntax/Lottery.java
> +    }
1. Lottery shouldn't extend ColorSupplier, it depends on it
2. Magic numbers should be extracted to constants with proper naming
3. Services we rely on are better as class variables in order not to create new object each time method is called
4. Do not use static methods unless it's really necessary
```suggestion
public class Lottery {
    private static final int MAX_BALL_NUMBER = 100;

    private final Random random = new Random();
    private final ColorSupplier colorSupplier = new ColorSupplier();

    public Ball getRandomBall() {
        int randomNumber = random.nextInt(MAX_BALL_NUMBER);
        Ball ball = new Ball(colorSupplier.getRandomColor(), randomNumber);
        return ball;
    }
```

2023-07-24 17:23 UTC, olekskov commented on src/main/java/core/basesyntax/ColorSupplier.java
>      }
Please rework according to comments left to Lottery class

2023-07-24 17:23 UTC, olekskov commented on src/main/java/core/basesyntax/Ball.java
> +    public Ball(Enum color, int number) {
```suggestion
    public Ball(Color color, int number) {
```

2023-07-24 17:23 UTC, olekskov commented on src/main/java/core/basesyntax/Ball.java
> +    private Enum color;
```suggestion
    private Color color;
```

2023-07-30 09:55 UTC, Ivan95kos requested changes
Please, fix all checks
<img width="858" alt="Знімок екрана 2023-07-30 о 12 54 34" src="https://github.com/mate-academy/jv-lottery/assets/41166578/63c661e1-9f45-4fe2-8819-b71a335a6e1f">

2023-08-15 16:08 UTC, Ivan95kos requested changes
Good job overall!

2023-08-16 08:47 UTC, okuzan approved these changes
Well done!

2025-08-24 12:08 UTC, closed without merging