Added jv-lottery solution
mate-academy/jv-lottery pull request #1068
Opened 2023-08-07 07:56 UTC by Stanislav-Viner

2023-08-07 10:01 UTC, okuzan requested changes
Good job on your first attempt!

2023-08-07 10:01 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +        int index = new Random().nextInt(100) + 1;
make ColorSupplier (and Random) class field, not a local variable
make 100 a class constant
rename uninformative `str` to `color`

2023-08-08 09:27 UTC, olekskov commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
same here

2023-08-08 14:35 UTC, kozhukhovsky requested changes

2023-08-08 14:35 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Application.java
> +        }
```suggestion
        Lottery lottery = new Lottery();
        for (int i = 0; i < 3; i++) {
            System.out.println(lottery.getRandomBall());
        }
```

2023-08-08 14:35 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
>  public class ColorSupplier {
You misunderstood the previous comment a bit. No need to move the index calculation here. Just the Random object itself.

2023-08-08 14:35 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private int index = new Random().nextInt(Color.values().length);
```suggestion
    Random random = new Random();
```

2023-08-08 14:35 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[index].name();
```suggestion
        return Color.values()[random.nextInt(Color.values().length)].name();
```

2023-08-08 14:35 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +    private int number = new Random().nextInt(MAX_NUMBER) + 1;
same as previous class

2023-08-08 17:22 UTC, kozhukhovsky approved these changes
Good job!

2023-08-08 17:31 UTC, closed without merging