Created a Ball class with the following fields: color and number and …
mate-academy/jv-lottery pull request #1081
Opened 2023-08-08 20:02 UTC by Eugene-Yukhimenko

…replaced the toString() method, also created an enum with different colors.

  Implemented the getRandomColor() method in the ColorSupplier class, this method returns a random color based on enum values.
  Created a Lottery class with a getRandomBall() method that returns a ball, this method creates a ball with a random color and a random number, the maximum number being 100.
 Tested the program in the main() method.

2023-08-09 09:52 UTC, okuzan requested changes

2023-08-09 09:52 UTC, okuzan commented on src/main/java/Lottery.java
> +        int randomNumber = random.nextInt(100);
Random and ColorSupplier should be class field, don't forget about appropriate access modifier
100 should be class constant, don't forget about CONSTANT_CASE

2023-08-09 09:52 UTC, okuzan commented on src/main/java/Main.java
> +
we need to create only one lottery instance, and then we call its method in a for loop

2023-08-10 10:31 UTC, olekskov requested changes

2023-08-10 10:31 UTC, olekskov commented on src/main/java/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
Random should be class field same as in Lottery class in order not to create new object each time method is called

2023-08-10 10:31 UTC, olekskov commented on src/main/java/Lottery.java
> +    private final int maxNumber = 100;
constant are private static final and has UPPERCASE_NAMING
also it's better to place them before other variables
```suggestion
    private static final int MAX_NUMBER = 100;

    private final Random random = new Random();
    private final ColorSupplier colorSupplier = new ColorSupplier();
```

2023-08-12 14:30 UTC, olekskov approved these changes
Good job

2025-02-06 09:05 UTC, closed without merging