I've finished this task. Can you please check it?
mate-academy/jv-lottery pull request #1097
Opened 2023-08-13 17:13 UTC by IvanIKS

2023-08-14 09:32 UTC, Rommelua requested changes
https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there.

2023-08-14 09:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(ball.toString());
```suggestion
            System.out.println(ball);
```

2023-08-14 09:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Color.java
> +    Yellow,
uppercase

2023-08-14 09:32 UTC, Rommelua commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        Random random = new Random();
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/6b971c2f-6117-4f5a-8758-aa3e4d9f1468)

2023-08-14 09:32 UTC, Rommelua commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return "" + color;
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/6f7776b7-5ffb-4540-9d51-75fd488a3d2f)

2023-08-14 17:11 UTC, IvanIKS commented
I have revorked the code in the way you suggested: used "ball" instead of "ball.toString", changed text to uppercase, used .name() and moved Random to class level. Can you please check the task again?

2023-08-16 16:07 UTC, closed without merging

2023-08-18 09:55 UTC, Rommelua requested changes

2023-08-18 09:55 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +        ball.setNumber(random.nextInt(100));
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/5d61bf57-956c-4cc7-bd0a-fe69c0dcf4ca)

2023-08-18 14:53 UTC, IvanIKS commented
I've changed "100" with variable "maxNumber" that represents the maximal number of ball. Can you please check it?

2023-08-18 16:10 UTC, sokimaaa requested changes

2023-08-20 08:24 UTC, IvanIKS commented
I'm sorry I did not commited it earlier.

2023-08-20 09:30 UTC, sokimaaa approved these changes