Created Ball class that contains information about Ball and overrided…
mate-academy/jv-lottery pull request #1113
Opened 2023-08-26 20:30 UTC by Trayvor

… method toString(). Created enum Color that contains colors for balls and CollorSupplier class that return a random color. Created Lottery class that use ColorSupplier to generate random color for ball and also generates a random number for ball. In Application class inizializated main method that create and print information about 3 unique balls.

2023-08-27 09:50 UTC, olekskov requested changes

2023-08-27 09:50 UTC, olekskov commented on src/main/java/core/basesyntax/Application.java
> +        }
Please combine and perform filling and printing in one cycle

2023-08-27 09:50 UTC, olekskov commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
Please extract random as class variable same as done in Lottery class in order not to create new object each time method is called

2023-08-27 09:50 UTC, olekskov commented on src/main/java/core/basesyntax/Lottery.java
> +        int ballNumber = randomNumber.nextInt(100);
Please extract magic numbers to constants with proper naming

2023-08-28 09:32 UTC, Trayvor commented
I added everything you suggested. What changes are requested?

2023-08-28 10:09 UTC, okuzan requested changes

2023-08-28 10:09 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
>      }
we don't need an array, call print on the object returned by getRandomBall method rightaway :)
toString is called on object being printed by default, it's redundant

2023-08-28 10:09 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(ballColor.toString(), ballNumber);
```suggestion
    static final int MAX_BALL_NUMBER = 100;
    private Random randomNumber = new Random();
    private ColorSupplier randomColor = new ColorSupplier();

    public Ball getRandomBall() {
        int ballNumber = randomNumber.nextInt(MAX_BALL_NUMBER);
        Color ballColor = randomColor.getRandomColor();
        return new Ball(ballColor.name(), ballNumber);
```

2023-08-28 10:09 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +        Ball[] ballArray = new Ball[3];
better extract 3 to a class constant and use it in for loop

2023-08-28 16:27 UTC, olekskov approved these changes
Good job

2024-11-10 17:54 UTC, closed without merging