Home_task_lottery_try_#1
mate-academy/jv-lottery pull request #1204
Opened 2023-10-12 18:51 UTC by slava-moiseev-kramatorsk

2023-10-13 09:33 UTC, kozhukhovsky requested changes
https://github.com/mate-academy/jv-lottery/blob/master/checklist.md

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Ball.java
> +
```suggestion
```

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Colors.values().length);
move Random to the class field

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Colors.values()[index].toString();
see checklist
use name()

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
```suggestion
public enum Color {
```
all class name in singular

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +
```suggestion
```

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +
```suggestion
```

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +
```suggestion
```

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(new Random().nextInt(100), new ColorSupplier().getRandomColor().toString());
```suggestion
        return new Ball(new Random().nextInt(100), new ColorSupplier().getRandomColor());
```

no need again getting string. You are return string from method getRandomColor()

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(new Random().nextInt(100), new ColorSupplier().getRandomColor().toString());
move random and colorsupplier to the class field

2023-10-13 09:33 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(new Random().nextInt(100), new ColorSupplier().getRandomColor().toString());
make 100 as class constant

2023-10-13 17:00 UTC, okuzan requested changes
Good job so far!

2023-10-13 17:00 UTC, okuzan commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private final int index = random.nextInt(Color.values().length);
You need to generate a new index for each method invocation - you currently generate it only once, when the class is created, and then getRandomColor returns that color each time the method is called. Make it a local variable instead

2023-10-14 07:06 UTC, slava-moiseev-kramatorsk commented on src/main/java/core/basesyntax/Lottery.java
> +    private final int maxBalls = 100;
![image](https://github.com/mate-academy/jv-lottery/assets/94477184/e611683e-d844-4f62-9101-23b9aa577be6)

2023-10-14 07:09 UTC, slava-moiseev-kramatorsk commented on src/main/java/core/basesyntax/Lottery.java
> +    private final int maxBalls = 100;
Intellij recommends moving it to a method

2023-10-14 09:38 UTC, olekskov approved these changes
Good job

2023-10-14 10:01 UTC, closed without merging