Develop/student
mate-academy/jv-lottery pull request #1241
Opened 2023-11-11 10:57 UTC by banderan

2023-11-11 10:59 UTC, banderan commented
Finish, program works and mvn clean package shows success

2023-11-12 15:32 UTC, Rommelua requested changes

2023-11-12 15:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Application.java
> +        Ball[] balls = new Ball[3];
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/99c5e27a-5095-41c8-9e55-95df8c16c704)

2023-11-12 15:32 UTC, Rommelua commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return colors[randomColor].toString();
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/6bfca400-6b47-4c01-8455-1a52c62a841c)

2023-11-12 15:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Number.java
> +public class Number {
Better delete this class and use Random in class Lottery

2024-02-28 16:14 UTC, closed without merging