Added solution to the task.
mate-academy/jv-lottery pull request #1308
Opened 2024-01-03 20:37 UTC by yanna-stepanova

2024-01-04 10:05 UTC, okuzan requested changes
Good job overall!

2024-01-04 10:05 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +        }
toString is called under the hood automatically
try to rewrite this without using array and creating only one lottery instance, not 3

2024-01-04 10:05 UTC, okuzan commented on src/main/java/core/basesyntax/Ball.java
> +    }
we use `this` when we need to differentiate between a class field and an argument that share the same name, it's not the case here, so you can safely omit them

2024-01-04 10:05 UTC, okuzan commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
make random a private class-level field

2024-01-04 10:05 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(new ColorSupplier().getRandomColor(), new Random().nextInt(100));
make random a private class-level field
make color supplier a private class-level field
make 100 a private class-level constant

2024-01-04 19:08 UTC, olekskov requested changes
Oleh's comment was a bit misunderstood, please check comments to fix

2024-01-04 19:08 UTC, olekskov commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    }
```suggestion
```

2024-01-04 19:08 UTC, olekskov commented on src/main/java/core/basesyntax/Lottery.java
> +    }
```suggestion
public class Lottery {
    private static final int MAX_NUMBER = 100;

    private Random random = new Random();
    private ColorSupplier colorSupplier = new ColorSupplier();
    
    public Ball getRandomBall() {
        return new Ball(colorSupplier.getRandomColor(), random.nextInt(MAX_NUMBER));
    }
```

2024-01-04 19:08 UTC, olekskov commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = getRandom().nextInt(Color.values().length);
```suggestion
        int index = random.nextInt(Color.values().length);
```

2024-01-05 10:21 UTC, okuzan requested changes

2024-01-05 10:21 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +        System.out.println(Arrays.toString(balls));
it's an interesting approach, but let's use a for loop for this, as mentioned in the [checklist](https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery)
![image](https://github.com/mate-academy/jv-lottery/assets/49767049/b2461e52-9d64-4808-83ad-83bf76f60ec1)

2024-01-05 11:32 UTC, okuzan requested changes
review for sync with the platform

2024-01-05 13:44 UTC, okuzan requested changes
let's print balls directly in the loop

2024-01-05 13:44 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +        System.out.println(Arrays.toString(balls));
```suggestion
        for (int i = 0; i < BOUND; i++) {
             System.println(lottery.getRandomBall());
        }
```

2024-01-05 13:50 UTC, yanna-stepanova commented
Should  the lottery instance be as a private class-level field in Application.java?

2024-01-05 14:09 UTC, okuzan approved these changes
Well done! Best of luck on your educational journey 🤞 🚀

2024-01-05 14:09 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +    private static Lottery lottery = new Lottery();
not necessary, but ok

2024-01-05 14:42 UTC, closed without merging