task complited
mate-academy/jv-lottery pull request #1392
Opened 2024-02-27 03:00 UTC by david-vozniak

2024-02-27 11:39 UTC, Vasul-Pankiv requested changes

2024-02-27 11:39 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
```suggestion
public enum Color {

```

2024-02-27 11:39 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return String.valueOf(colors);
```suggestion
        return Colors.values()[index].name();
```

2024-02-27 11:39 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/Lottery.java
> +        int ballIndex = new Random().nextInt(100);
make magic number constant

2024-02-27 11:39 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    public static String getRandomColor() {
do not make it static, create an instance of supplier where you need it

2024-02-27 11:39 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/Lottery.java
> +    public static String getRandomBall() {
```suggestion
    public Ball getRandomBall() {

```

2024-02-27 11:39 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/Application.java
> +        System.out.println(getRandomBall());
use cicle

2024-03-05 16:12 UTC, david-vozniak commented
could you check my code, please?

2024-07-06 08:24 UTC, MentorMateAcademy requested changes

2024-07-06 08:24 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/Application.java
> +
```suggestion
```

2024-07-06 08:24 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    public static String getRandomColor() {
```suggestion
    public String getRandomColor() {
```

2024-07-06 08:24 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/Lottery.java
> +        final int bound = 100;
magic number

2024-07-06 08:24 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/Lottery.java
> +        int ballIndex = new Random().nextInt(bound);
don`t create random object inside method

2024-07-16 06:05 UTC, david-vozniak commented
I hope my edits make some sense. Otherwise, I don’t quite understand what is required of me

2024-07-16 06:37 UTC, Elena-Bruyako requested changes

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(new Lottery().getRandomBall());
Don't create Lottery object in a loop

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Application.java
> +        for (int i = 0; i < 3; i++) {
3 is a magic number, create constant

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
Random should be class-level variable

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[index].toString();
don't use toString for enum
```suggestion
        return Color.values()[index].name();
```

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +    public int getRandomNumber() {
```suggestion
    private int getRandomNumber() {
```

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +    public static final int MAX_BOUND = 100;
```suggestion
    public static final int MAX_BOUND = 100;
    private final Random random = new Random();
    private final ColorSupplier colorSupplier = new ColorSupplier();
```

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +    public int getRandomNumber() {
Replace after public method

2024-07-16 06:37 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(getRandomColor(), getRandomNumber());
```suggestion
        return new Ball(colorSupplier.getRandomColor(), getRandomNumber());

```

2024-07-16 18:00 UTC, Sanderfuck requested changes

2024-07-16 18:02 UTC, MentorMateAcademy requested changes
fix prev comments

2024-07-16 18:46 UTC, david-vozniak commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private final int randomNumber = new Random().nextInt(Color.values().length);
'Random should be class-level variable'. That was the previous mentor request. That`s why I made "Random" a variable.

2024-07-16 18:49 UTC, david-vozniak commented
Why do I get review from different mentor, when I made request only to previous. It doesn't appears to be comfortable. Can we stick with only a couple?

2024-07-17 09:15 UTC, MentorMateAcademy requested changes

2024-07-17 09:15 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/Lottery.java
> +    private int getRandomNumber() {
not fixed, you have private above public method

2024-07-17 09:15 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[new Random().nextInt(Color.values().length)].name();
```suggestion
        return Color.values()[random.nextInt(Color.values().length)].name();
```

2024-07-17 09:15 UTC, MentorMateAcademy commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[new Random().nextInt(Color.values().length)].name();
Make it like this 
![image](https://github.com/user-attachments/assets/c3014aaa-cc52-428e-8db8-6930f5b18de1)

2024-07-18 14:25 UTC, MentorMateAcademy approved these changes

2024-07-19 01:07 UTC, closed without merging