Created a Ball class with fields: color,number. Override toString met…
mate-academy/jv-lottery pull request #1422
Opened 2024-03-17 18:37 UTC by mhvaleria

…hod.Created a Lottery which will return the ball with a random color and number.

2024-03-17 18:54 UTC, okuzan requested changes
Good job overall!

2024-03-17 18:54 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +
Here, you should create balls inside a for loop

2024-03-17 18:54 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +    }
should be in Application.java
naming with numbers is a sign something is wrong - here, you should do this in a loop

2024-03-17 18:54 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +        int randomNumber = new Random().nextInt(101);
101 - should be a class-level constant, random - a class-level field

2024-03-17 18:54 UTC, okuzan commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        Random random = new Random();
same for this random

2024-03-17 18:54 UTC, okuzan commented on src/main/java/core/basesyntax/Color.java
> +    WHITE("white");
not a mistake but I don't see much point in having the same colorname as enum value but in lowercase, we can call .lowercase() on enum.name()

2024-03-18 10:49 UTC, Rommelua requested changes

2024-03-18 10:49 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +    private static final int MAX = 101;
```suggestion
    private static final int MAX_BALL_NUMBER = 101;
```

2024-03-18 10:49 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +    public static Ball getRandomBall() {
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/46288164-6220-4897-8b2b-c501d0b1d985)

2024-03-18 10:49 UTC, Rommelua commented on src/main/java/core/basesyntax/Color.java
> +    }
```suggestion
```

2024-03-19 10:47 UTC, kozhukhovsky approved these changes
Approve, because its last attempt. But need fix :)

2024-03-19 10:47 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Color.java
> +    public String
what with formatting?

2024-03-19 10:47 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +    public static Ball getRandomBall() {
nor fixed

2024-03-19 10:47 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +        int randomNumber = new Random().nextInt(MAX_BALL_NUMBER);
move Random to the class field

2025-01-02 11:44 UTC, closed without merging