Created Classes and wrote methods as described in the task
mate-academy/jv-lottery pull request #1449
Opened 2024-04-10 03:23 UTC by Jacalius

2024-04-10 11:13 UTC, Rommelua requested changes
Before you create PR with your homework, you need to go through the checklist under the task and correct all the points described there. The mentor will not check the work until the checklist points are corrected

2024-04-10 11:13 UTC, Rommelua commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(randomBall.toString());
```suggestion
            System.out.println(randomBall);
```

2024-04-10 11:13 UTC, Rommelua commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/cc216680-7d40-46d9-892e-61f46817939b)

2024-04-10 11:13 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +        int ballNumber = random.nextInt(100);
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/cb49dbfc-df47-4880-a252-6a02d0f2bc18)

2024-04-11 09:32 UTC, Rommelua requested changes

2024-04-11 09:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(color.getRandomColor().toString(), ballNumber);
![image](https://github.com/mate-academy/jv-lottery/assets/20326858/ffedbfb0-822a-4fbf-b074-c7507e85f08f)

2024-04-11 17:26 UTC, MentorMA requested changes

2024-04-11 17:26 UTC, MentorMA commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[index];
Return color in String Type

2024-04-11 17:26 UTC, MentorMA commented on src/main/java/core/basesyntax/Ball.java
> +    }
If you not use you can clear this methods

2024-04-11 18:01 UTC, MAMentorFX requested changes

2024-04-11 18:01 UTC, MAMentorFX commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[index];
not fixed

2024-04-11 18:01 UTC, MAMentorFX commented on src/main/java/core/basesyntax/Lottery.java
> +        int ballNumber = random.nextInt(MAXIMUM_POSSIBLE_NUMBER);
random.nextInt() returns 0 inclusively and 100 exclusively

2024-04-12 09:26 UTC, MentorMA approved these changes

2024-10-21 15:41 UTC, closed without merging