Lottery
mate-academy/jv-lottery pull request #1468
Opened 2024-04-22 13:23 UTC by mgsorigo

2024-04-23 07:41 UTC, nowickimj requested changes
Changes required - please check the requirements for this task

2024-04-23 07:41 UTC, nowickimj commented on src/main/java/core/basesyntax/Lottery.java
> +        ColorSupplier colorSupplier = new ColorSupplier();
`colorSupplier` should be a constant

2024-04-23 07:41 UTC, nowickimj commented on src/main/java/core/basesyntax/Lottery.java
> +        Random random = new Random();
`random` should be a constant

2024-04-23 07:41 UTC, nowickimj commented on src/main/java/core/basesyntax/Lottery.java
> +        int number = random.nextInt(100) + 1;
Max number should be a constant (e.g. `MAX_NUMBER`)

2024-04-23 07:41 UTC, nowickimj commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        Random random = new Random();
`random` should be a constant

2024-04-23 07:41 UTC, nowickimj commented on src/main/java/core/basesyntax/Lottery.java
> +    public static Ball getRandomBall() {
This method shouldn't be static

2024-04-23 07:41 UTC, nowickimj commented on src/main/java/core/basesyntax/Application.java
> +        ColorSupplier colorSupplier = new ColorSupplier();
You shouldn't create `ColorSupplier` instance here.
Please read carefully the requirements for this exercise.

2024-04-23 09:11 UTC, mgsorigo commented
@nowickimj The changes have been implemented. Request for review.

2024-04-29 07:29 UTC, nowickimj requested changes
Looks good, one more thing to fix

2024-04-29 07:29 UTC, nowickimj commented on src/main/java/core/basesyntax/Application.java
> +        System.out.println("Ball 3: " + ball3);
Repetitive tasks should be handled in the loop:
https://github.com/mate-academy/jv-lottery/blob/master/checklist.md#use-for-loop-for-creating-several-objects-of-the-same-class

2024-04-29 09:07 UTC, nowickimj approved these changes

2024-05-21 13:54 UTC, closed without merging