jv-lottery
mate-academy/jv-lottery pull request #1483
Opened 2024-05-01 21:21 UTC by Ppllupold

2024-05-02 05:43 UTC, Elena-Bruyako requested changes
Please, read carefully Common mistakes file before you create PR

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +    public static Ball getRandomBall() {
[Don’t use static methods in your solution](https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery#dont-use-static-methods-in-your-solution)

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Application.java
> +
[Please don’t add redundant empty lines to your code.](https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery#please-dont-add-redundant-empty-lines-to-your-code)

Check everywhere

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(ColorSupplier.getRandomColor().name().toLowerCase(),
[Think about which variables should be local in the method and which should be class-level](https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery#think-about-which-variables-should-be-local-in-the-method-and-which-should-be-class-level)

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +                new Random().nextInt(101));
[All magic numbers in your code should be constants.](https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery#all-magic-numbers-in-your-code-should-be-constants)

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
read naming convention for enum
```suggestion
public enum Color {
```

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Colors.java
> +    RED, BLUE, GREEN;
```suggestion
    RED, BLUE, GREEN
```

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Ball.java
> +public class Ball {
Don't create methods that you actually don't use

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    public static Colors getRandomColor() {
```suggestion
    public Colors getRandomColor() {
```

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int randomColor = new Random().nextInt(Colors.values().length);
new Random() class-level variable

2024-05-02 05:43 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Application.java
> +        for (int i = 0; i < 10; i++) {
10 is a magic number, create constant

2024-05-04 05:25 UTC, Elena-Bruyako requested changes
Please, don't resolve comments by yourself

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(new Lottery().getRandomBall());
Don't need to create new Lottery() object in a loop.

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Ball.java
> +
```suggestion
```

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private int randomColor = new Random().nextInt(Color.values().length);
```suggestion
    private final Random random = new Random();

    public String getRandomColor() {
        int index = random.nextInt(Color.values().length);
        return Color.values()[index].name().toLowerCase();
    }
```

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +    private static final int rand = 101;
Bad naming - rand. For example, MAX_BALL_NUMBER
Also, read constant convention: Constant names are to be written in uppercase with an underscore separating the words.

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +    private Color color = new ColorSupplier().getRandomColor();
```suggestion
    private final Random random = new Random();
    private final ColorSupplier colorSupplier = new ColorSupplier();
```

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(color.name().toLowerCase(),
```suggestion
        return new Ball(colorSupplier.getRandomColor(),
```

2024-05-04 05:25 UTC, Elena-Bruyako commented on src/main/java/core/basesyntax/Lottery.java
> +                new Random().nextInt(rand));
```suggestion
                random.nextInt(MAX_BALL_NUMBER));
```

2024-05-04 11:59 UTC, okuzan requested changes

2024-05-04 11:59 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +                random.nextInt(101));
why don't you use your constant?

2024-05-04 11:59 UTC, okuzan commented on pom.xml
> +        <jdk.version>11</jdk.version>
why?

2024-05-04 16:34 UTC, sarakhmen approved these changes
Good job :)

2024-05-04 16:34 UTC, sarakhmen commented on pom.xml
> +        <jdk.version>11</jdk.version>
please revert this version

2024-05-04 16:36 UTC, sarakhmen approved these changes
Good job:)

2024-05-06 17:11 UTC, closed without merging