refactored hw lottery
mate-academy/jv-lottery pull request #557
Opened 2022-10-11 22:02 UTC by Watxesnavo

2022-10-12 15:01 UTC, aaananas requested changes

2022-10-12 15:01 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +        ColorSupplier supplier = new ColorSupplier();
lets make ColorSupplier a global variable, so it is going to be created just once instead of each time this method is invoked

2022-10-12 15:01 UTC, aaananas commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return colors[new Random().nextInt(colors.length)].toString();
lets make Random a global variable, so it is going to be created just once instead of each time this method is invoked

2022-10-12 15:01 UTC, aaananas commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
```suggestion
public enum Color {
```

2022-10-20 13:12 UTC, aaananas requested changes

2022-10-20 13:12 UTC, aaananas commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return colors[random.nextInt(colors.length)].toString();
![image](https://user-images.githubusercontent.com/81781479/196958001-867daca6-5e9f-4502-a044-123d46d49c10.png)

2022-10-20 13:12 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(supplier.getRandomColor(), new Random().nextInt(100));
lets make Random global too

2022-10-20 13:12 UTC, aaananas commented on src/main/java/core/basesyntax/Application.java
> +        for (int i = 0; i < 3; i++) {
```suggestion
        for (int i = 0; i < BALL_NUMBER; i++) {
```
don't use magic numbers

2022-10-20 13:12 UTC, aaananas commented on src/main/java/core/basesyntax/Application.java
>          // create three balls using class Lottery and print information about them in console
remove comment

2022-10-21 11:23 UTC, Rommelua requested changes

2022-10-21 11:23 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(supplier.getRandomColor(), random.nextInt(100));
[Common mistakes](https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery)
**All magic numbers in your code should be constants.**
Make 100 constant.

2022-10-21 11:23 UTC, Rommelua commented on src/main/java/core/basesyntax/Application.java
> +
empty line

2022-10-21 14:44 UTC, aaananas approved these changes
for future - dont forget to create a separate branch for your solution

2024-10-31 17:46 UTC, closed without merging