solution
mate-academy/jv-lottery pull request #636
Opened 2022-12-05 21:07 UTC by Richaa2

2022-12-07 15:06 UTC, MaliukDaria requested changes

2022-12-07 15:06 UTC, MaliukDaria commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        Random random = new Random();
lets make Random as class level variable, not to create new instance of Random class every time we call getRandomColor() method

2022-12-07 15:06 UTC, MaliukDaria commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
```suggestion
public enum Color {
```

2022-12-07 15:06 UTC, MaliukDaria commented on src/main/java/core/basesyntax/Lottery.java
> +        return ball;
same, let's make Random and ColorSupplier as class level variables, not to create new instances every time we call getRandomBall() method. And lets make number 100 as constant field https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names

2022-12-07 16:33 UTC, Andr1yK requested changes
test

2022-12-08 13:57 UTC, aaananas approved these changes

2022-12-08 13:57 UTC, aaananas commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        Color values = Color.values()[random.nextInt(lengthOfColors)];
```suggestion
        Color color = Color.values()[random.nextInt(lengthOfColors)];
```

2022-12-08 13:57 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +        ball.setNumber(random.nextInt(NUMBER));
```suggestion
        ball.setNumber(random.nextInt(MAX_NUMBER));
```

2023-01-07 11:18 UTC, closed without merging