Home work Lottery
mate-academy/jv-lottery pull request #687
Opened 2022-12-28 15:41 UTC by IParov

2022-12-28 17:45 UTC, aaananas requested changes

2022-12-28 17:45 UTC, aaananas commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(balls[i].toString());
```suggestion
            System.out.println(balls[i]);
```
toString is called by default

2022-12-28 17:45 UTC, aaananas commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
```suggestion
public enum Color {
```

2022-12-28 17:45 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +        int bound = 100;
make it a constant `private static final`

2022-12-28 18:32 UTC, Rommelua requested changes

2022-12-28 18:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +    private static final Ball BALL = new Ball();
```suggestion
```

2022-12-28 18:32 UTC, Rommelua commented on src/main/java/core/basesyntax/Lottery.java
> +    public Ball getRandomBall() {
create new ball here

2022-12-28 19:03 UTC, Rommelua approved these changes

2022-12-29 10:28 UTC, Rommelua approved these changes
Одного аппрува достаточно, больше запрашивать не нужно)
![image](https://user-images.githubusercontent.com/20326858/209938551-4b30b362-249d-44ad-a757-e2d8deebe40d.png)

2024-07-18 12:36 UTC, closed without merging