added class Ball, Lottery and enum DifferentColor realization metod g…
mate-academy/jv-lottery pull request #701
Opened 2023-01-03 11:20 UTC by bigvini

…etRandomColor in class ColorSupplier. realozation metod getRandomBall in class Lottery

2023-01-03 17:40 UTC, okuzan requested changes

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(ball.toString());
this could be one-liner, and you need just one Lottery instance, don't recreate it every time

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/Ball.java
> +    }
unused contstructor

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(DifferentColor.values().length);
make this instance variable instead of recreating Random object each time method's called

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/DifferentColor.java
> +public enum DifferentColor {
```suggestion
public enum Color {
```

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +        int number = new Random().nextInt(100);
magic number => constant

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return DifferentColor.values()[index].toString();
https://mate-academy.github.io/jv-program-common-mistakes/java-core/oop/lottery#use-name-for-getting-string-representation-of-enum-constants

2023-01-03 17:40 UTC, okuzan commented on src/main/java/core/basesyntax/Lottery.java
> +        int number = new Random().nextInt(100);
make this instance variable instead of recreating Random object each time method's called

2023-01-04 12:39 UTC, nacenik requested changes

2023-01-04 12:39 UTC, nacenik commented on src/main/java/core/basesyntax/Ball.java
> +    public String getColor() {
delete getters and setters, cause they are useless

2023-01-04 12:39 UTC, nacenik commented on src/main/java/core/basesyntax/Lottery.java
> +    Random random = new Random();
Add access modifiers

2023-01-04 12:39 UTC, nacenik commented on src/main/java/core/basesyntax/Lottery.java
> +    final int maxNumber = 100;
Add access modifiers and [rename according to the convensions](https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names)

2023-01-04 12:39 UTC, nacenik commented on src/main/java/core/basesyntax/Lottery.java
> +        String color = new ColorSupplier().getRandomColor();
ColorSupplier should be a class-field

2023-01-04 12:39 UTC, nacenik commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    Random random = new Random();
Add access modifiers

2023-01-05 15:57 UTC, aaananas requested changes

2023-01-05 15:57 UTC, aaananas commented on src/main/java/core/basesyntax/Application.java
> +            System.out.println(lottery.getRandomBall().toString());
```suggestion
            System.out.println(lottery.getRandomBall());
```
toString is called automatically inside System.out.println()

2023-01-05 15:57 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +public class Lottery {
```suggestion
public class Lottery {
     private static final int MAX_NUMBER = 100;
```

2023-01-05 15:57 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +        final int maxNumber = 100;
```suggestion
```

2023-01-05 15:57 UTC, aaananas commented on src/main/java/core/basesyntax/Lottery.java
> +    private ColorSupplier colorSupplier;
```suggestion
    private ColorSupplier colorSupplier = new ColorSupplier();
```

2023-01-06 15:21 UTC, aleksandr-bevza approved these changes

2025-02-20 22:14 UTC, closed without merging