hw-2-lottery
mate-academy/jv-lottery pull request #796
Opened 2023-02-13 17:21 UTC by VolodymyrDavidov

2023-02-13 23:35 UTC, uliana-andrushchuk requested changes

2023-02-13 23:35 UTC, uliana-andrushchuk commented on src/main/java/core/basesyntax/Color.java
> +    Red,
Enum members are constants. You should use uppercase here

2023-02-13 23:35 UTC, uliana-andrushchuk commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[index].toString();
It's better to use `name()` for getting String representation of enum constants

2023-02-13 23:35 UTC, uliana-andrushchuk commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Color.values()[index].toString();
`Color.values()` can be extracted as separate variable, as it's used twice

2023-02-15 16:30 UTC, aleksandr-bevza requested changes

2023-02-15 16:30 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return getColor[index].name();
1. getColor is a good name for method, but not for variable.
2. Move Random to class field. Don't create new Random each time this method is invoked.
```suggestion
        Color[] colorValues = Color.values();
        int index = random.nextInt(colorValues.length);
        return getColor[index].name();
```

2023-02-15 16:30 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/Lottery.java
> +    private static final int NUMBER = 100;
Variable's name should explain it's purpose
```suggestion
    private static final int NUMBER_LIMIT = 100;
```

2023-02-15 16:30 UTC, aleksandr-bevza commented on src/main/java/core/basesyntax/Lottery.java
> +
```suggestion
```

2023-02-15 18:43 UTC, closed without merging