Solution jv-lottery task
mate-academy/jv-lottery pull request #804
Opened 2023-02-20 19:50 UTC by MaxMeleshchenko

2023-02-20 20:01 UTC, Ivan95kos requested changes
fix all checks
<img width="867" alt="Знімок екрана 2023-02-20 о 22 00 48" src="https://user-images.githubusercontent.com/41166578/220189639-8e492393-076d-4b16-9b72-70fa76e47e77.png">

2023-02-21 11:09 UTC, kozhukhovsky requested changes

2023-02-21 11:09 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Application.java
> +        }
```suggestion
        for (int i = 0; i < 3; i++) {
            System.out.println(lottery.getRandomBall());
        }
```

2023-02-21 11:09 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Application.java
> +
remove empty line

2023-02-21 11:09 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        int index = new Random().nextInt(Color.values().length);
move Random to the class field, like:
![image](https://user-images.githubusercontent.com/12864128/220328721-f24bbd91-9f17-489a-a49f-ba58323f4ee1.png)

2023-02-21 11:09 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +        ColorSupplier colorSupplier = new ColorSupplier();
Move CollorSupplier and Random to the class field

2023-02-21 11:09 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +        ball.setNumber(new Random().nextInt(100));
100 is magic number
![image](https://user-images.githubusercontent.com/12864128/220328881-84ca8d79-14d7-49da-8fac-a2141e7d2650.png)

2023-02-21 11:09 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/Lottery.java
> +
remove empty line

2023-02-21 12:01 UTC, MaxMeleshchenko commented on src/main/java/core/basesyntax/Application.java
> +
Throws an error when deleting an empty line : [NewlineAtEndOfFile]

2023-02-23 14:56 UTC, kozhukhovsky approved these changes

2024-10-23 08:57 UTC, closed without merging