HW-Lottery
mate-academy/jv-lottery pull request #983
Opened 2023-06-27 17:08 UTC by CodeWebWeaver

Created requested classes and implemented method getRandomBall() in Lottery class

2023-06-29 12:01 UTC, andrii-hoienko requested changes
Added some comments, hope you can manage them fast)

2023-06-29 12:01 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/ColorSupplier.java
> +        return Colors.values()[randomColor.nextInt(Colors.values().length)];
Overloaded expression, please introduce some variables

2023-06-29 12:01 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/ColorSupplier.java
> +    private final Random randomColor = new Random();
variable randomColor should contain color from its name, I think you should rename it

2023-06-30 10:44 UTC, KseniiaMakarova requested changes
code style check failed
run `mvn clean package` before push

2023-06-30 10:44 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Colors.java
> +public enum Colors {
```suggestion
public enum Color {
```

2023-06-30 10:44 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Lottery.java
> +        return new Ball(randomNumber);
what about color?

2023-06-30 10:44 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Ball.java
> +        this.color = colorSupply.getRandomColor();
move this logic into getRandomBall() method

and add access modifier to constructor

2023-07-03 07:28 UTC, KseniiaMakarova requested changes

2023-07-03 07:28 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Ball.java
> +    Ball(Color color, int number) {
add access modifier

2023-07-03 07:28 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/Lottery.java
> +    private final ColorSupplier colorSupply = new ColorSupplier();
```suggestion
    private final ColorSupplier colorSupplier = new ColorSupplier();
```

2023-07-03 10:16 UTC, andrii-hoienko requested changes
Everything is good reagardind solution, but there are some unnecessary files in commit

2023-07-03 10:16 UTC, andrii-hoienko commented on .github/workflows/ci.yml
> +name: Java CI
Please dont push ( and dont change if it is not necessary) files which is not related to homework

2023-07-03 10:16 UTC, andrii-hoienko commented on README.md
> +This method should return a random color, based on the enum values (use `Random` class for this)
Please dont push ( and dont change if it is not necessary) files which is not related to homework

2023-07-03 10:16 UTC, andrii-hoienko commented on checklist.md
> -public class Main {
Please dont push ( and dont change if it is not necessary) files which is not related to homework

2023-07-03 10:16 UTC, andrii-hoienko commented on pom.xml
> -            <scope>test</scope>
Please dont push ( and dont change if it is not necessary) files which is not related to homework

2023-07-04 06:39 UTC, KseniiaMakarova approved these changes

2023-11-23 07:50 UTC, closed without merging